In [1]:
import mysql.connector
from mysql.connector import Error
import pandas as pd

# Fill in the database you want to work on
working_database = 'Retail'

# Fill in your mySQL root pass
my_password = 'dinh9Thuan'

try:
    connection = mysql.connector.connect(host='localhost',
                                         database=working_database,
                                         user='root',
                                         password=my_password)
    if connection.is_connected():
        db_info = connection.get_server_info()
        print('Connected to MySQL Server version ', db_info)
        cursor = connection.cursor()
        
        cursor.execute('select database();')
        record = cursor.fetchone()
        print('Connected to database: ', record)
        
        cursor.execute('show tables;')
        tables = cursor.fetchall()
        print('Tables in {} schema: {}'.format(working_database, tables))
        
        """TABLE disc_category"""
        print('\n', '* ' * 58, '\n')
        print('TABLE disc_category:\n')
        # Read products info from a data file (Products.csv) 
        disc_category = pd.read_csv('./retail/DiscountCategory.csv', header=None)
        
        # Generate an array of SQL's INSERT commands to add all entries in DiscountCategory.csv to Retail DB
        Q = ["INSERT INTO disc_category (category_ID, category, disc_percent) \
              VALUES ('{}', '{}', '{}');"\
             .format(f[0], f[1], f[2]) for f in disc_category.values]
        for q in Q:
            cursor.execute(q)
            
         # Run SELECT to show vendors table
        q = "SELECT * FROM disc_category;"
        cursor.execute(q)
        cursor.fetchall()
        table_disc = pd.read_sql_query(q, connection)
        print(table_disc)
        
        """TABLE vendors"""
        print('\n', '* ' * 58, '\n')
        print('TABLE vendors:\n')
        # Read vendors info from a data file (Vendors.csv) 
        vendors = pd.read_csv('./retail/Vendors.csv', header=None)
        
        # Generate an array of SQL's INSERT commands to add all entries in Vendors.csv to Retail DB
        Q = ["INSERT INTO vendors (vendor_ID, phone, email) \
              VALUES ('{}', '{}', '{}');"\
             .format(f[0], f[1], f[2]) for f in vendors.values]
        for q in Q:
            cursor.execute(q)
        
        # Run SELECT to show vendors table
        q = "SELECT * FROM vendors;"
        cursor.execute(q)
        cursor.fetchall()
        table_vendors = pd.read_sql_query(q, connection)
        print(table_vendors)
        
        # Run SELECT to show vendors table
        q = "SELECT * FROM products;"
        cursor.execute(q)
        cursor.fetchall()
        table_products = pd.read_sql_query(q, connection)
        print(table_products)
        
        """TABLE products"""
        print('\n', '* ' * 58, '\n')
        print('TABLE products:\n')
        # Read products info from a data file (Products.csv) 
        products = pd.read_csv('./retail/Products.csv', header=None)
        
        # Generate an array of SQL's INSERT commands to add all entries in Products.csv to Retail DB
        Q = ["INSERT INTO products (product_name, category_ID, unit_price) \
              VALUES ('{}', '{}', '{}');"\
             .format(f[0], f[1], f[2]) for f in products.values]
        for q in Q:
            cursor.execute(q)
        
        # Run SELECT to show vendors table
        q = "SELECT * FROM products;"
        cursor.execute(q)
        cursor.fetchall()
        table_products = pd.read_sql_query(q, connection)
        print(table_products)
        
        """TABLE buyers"""
        print('\n', '* ' * 58, '\n')
        print('TABLE buyers:\n')
        # Read buyers info from a data file (ClientInfo.csv) 
        client_info = pd.read_csv('./retail/ClientInfo.csv', header=None)
        
        # Generate an array of SQL's INSERT commands to add all entries in ClientInfo.csv to Retail DB
        Q = ["INSERT INTO buyers (first_name, last_name, login_ID, passw, phone, email, address) \
              VALUES ('{}', '{}', '{}', '{}', '{}', '{}', '{}');"\
             .format(f[0], f[1], f[2], f[3], f[4], f[5], f[6]) for f in client_info.values]
        for q in Q:
            cursor.execute(q)
        
        # Run SELECT to show buyers table
        q = "SELECT * FROM buyers;"
        cursor.execute(q)
        cursor.fetchall()
        table_buyers = pd.read_sql_query(q, connection)
        print(table_buyers)

except Error as e:
    print('Error while connecting to MySQL', e)

finally:
    if (connection.is_connected()):
        cursor.close()
        connection.close()
        print('\n', '* ' * 58, '\n')
        print('MySQL connection is closed.')

Connected to MySQL Server version  8.0.23
Connected to database:  ('retail',)
Tables in Retail schema: [('banks',), ('buyers',), ('cart',), ('disc_category',), ('invoices',), ('payments',), ('products',), ('supply_stock',), ('vendors',)]

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

TABLE disc_category:

   category_ID   category  disc_percent active
0            1   Cosmetic          10.0   None
1            2       DVDs           3.0   None
2            3  Keyboards          12.0   None
3            4    Glasses           0.0   None

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

TABLE vendors:

      vendor_ID        phone                  email
0        9Anime   4503324567       9Anime@gmail.com
1          Akai   4016584032         Akai@gmail.com
2        Alesis   4016585760       Alesis@gmail.com
3        AmiAmi  14243060591       AmiAmi@gmail.com
4     ArmNHamer  18004476666    ArmNHamer@gmail.com
5   CruncyhRoll   8189987104  CrunchyRoll@gmail.com
6          Dove   8188320643         Dove@gmail.com
7    Funimation   3109888765   FunImation@gmail.com
8         Gucci   8187374200        Gucci@gmail.com
9          Korg  16313906800         Korg@gmail.com
10        Nivea   9994563214        Nivea@gmail.com
11         Olay  18002855170     OlayMgmt@gmail.com
12      Pantene  18009457768         Pant@gmail.com
13        Prada   3102788661        Prada@gmail.com
14       Rayban   8187721353       RayBan@gmail.com
15   RightStuff  18003386827   RightStuff@gmail.com
16       Roland  13238903740       Roland@gmail.com
17      TomFord   3105505900      TomFord@gmail.com
18    Valentino   3102470103    Valentino@gmail.com
19       Yamaha   8668427080       Yamaha@gmail.com
Empty DataFrame
Columns: [item_ID, category_ID, product_name, unit_price]
Index: []

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

TABLE products:

    item_ID  category_ID      product_name  unit_price
0     10060            1  ExtraBlueShampoo        9.99
1     10061            1     GoldenShampoo        9.99
2     10062            1        CocoLotion       10.00
3     10063            1       Plainlotion        8.00
4     10064            1       Conditioner       12.00
5     10065            2            ReZero       50.00
6     10066            2           Saekano       50.00
7     10067            2            Naruto      100.00
8     10068            2     AttackOnTitan       20.00
9     10069            2          konosuba       50.00
10    10070            3         25keyMidi      100.00
11    10071            3         49KeyMidi      150.00
12    10072            3         64KeyMidi      300.00
13    10073            3         88KeyMidi      200.00
14    10074            3              Juno     1500.00
15    10075            4       ClearFrames      120.00
16    10076            4       BlackFrames      200.00
17    10077            4        BlueFrames      209.95
18    10078            4         RedFrames      211.95
19    10079            4        GoldFrames      500.00

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

TABLE buyers:

    buyer_ID first_name  last_name          login_ID               passw  \
0       1060      Sarah     Garner              2SSG            IamSarah
1       1061     Gracie    Leonard     GracieLeonard  NotASecurePassword
2       1062       Jack  Greenwood       GoldenGatez            Password
3       1063       Luke     Hilton         UpOnAHill            passWord
4       1064     Joshua   Faulkner        FalcoPunch          SuperSmash
5       1065       Rhys    Harding       HardlyAwake            ChipMunk
6       1066    Madison      Ellis          ElliGray    IForgetImADoctor
7       1067     Alicia     Parker  SpiderManIsMySon             Adopted
8       1068   Kayleigh   Fletcher         MarioKart          DoubleDash
9       1069      Tilly     Little         ImInAMall     UpsideDownStore
10      1070      Riley     Wilson       WillyWilson         ImAProducer
11      1071      Jacob      Davis           JJDavis                1234
12      1072     Jayden      Perry      KatiesCousin              ImRich
13      1073      Faith     Oliver   NoOlivesOnPizza        PepperFlakes
14      1074       Jack     Wright     LeftNotWright            FootBall
15      1075       Adam     Thomas     ImATankEngine         WatchMeOnTV
16      1076      Poppy      Adams     Married2Marry        WeArePoppins
17      1077  Sebastian       Dunn         DunDunDun            BeScared
18      1078        Kai    Spencer    SuspendesSpenc     Im2000FeetAbove
19      1079    Madison    Carroll      BasketCarrol     GreenDayIsABand

         phone                          email                  address
0    123456789                  ssG@gmail.com       10 Foregate Street
1   7750013401      GracieLeonard@teleworm.us         50 Layburn Court
2   8174594073     BillyWright@jourrapide.com      3220 Waldeck Street
3   6154724601          LukeHilton@dayrep.com    2081 Wilkinson Street
4   4088585823       JoshuaFaulkner@rhyta.com     3807 Sycamore Street
5   6627683408          RhysHarding@rhyta.com           3890 Rafe Lane
6   7757936173        MadisonEllis@dayrep.com  2057 Martha Ellen Drive
7   3305339364    AliciaParker@jourrapide.com       4862 Rainbow Drive
8   5106361825   KayleighFletcher@teleworm.us     2723 Clifford Street
9   5182449940        TillyLittle@armyspy.com            89 Ben Street
10  7048202801          RileyWilson@rhyta.com          378 Harry Place
11  9728333393          JacobDavis@dayrep.com          4222 Ash Street
12  5029633832        JaydenPerry@armyspy.com          3030 Karen Lane
13  4017803170         FaithOliver@dayrep.com         3730 Bond Street
14  9734892456           JackWright@rhyta.com      2463 Granville Lane
15  2173642845         AdamThomas@armyspy.com        1246 Bolman Court
16  3173303965         PoppyAdams@teleworm.us     4324 Crestview Manor
17  2147396205        SebastianDunn@rhyta.com       20 Carolyns Circle
18  4077746245         KaiSpencer@armyspy.com        2138 Grand Avenue
19  7405252633  MadisonCarroll@jourrapide.com         4117 Irving Road

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

MySQL connection is closed.